### ISSUE TITLE
Better config format

### ISSUE THREAD

**Issue by VicDeo** [VicDeo/go-obfuscate#2]
```
tables:
  # as is
  kept:
    - kept_table_1
    - kept_table_2
    ...
  # completely excluded
  ignored:
    - ignored_table_1
    - ignored_table_2
    ...
  # keep structure but wipe data
  truncated:
    - truncated_table_1
    - truncated_table_2
    ...

  # keep structure, obfuscate fields according to the column spec
  obfuscated:
    - obfuscated_table_1
      - column_1
      - column_2
      ...
    - obfuscated_table_2
      - column_1
      - column_2
      ...
    ...
```
