### ISSUE TITLE
column names in the obfuscate section are silently omited when they have no chlidren

### ISSUE THREAD

**Issue by VicDeo** [VicDeo/go-obfuscate#4]
A sample config file part:
```
tables:
  obfuscate:
    table_name:
      column_name_1:
      column_name_2:
        whatever
```
### Expected behavior
Validation error that **column_name_1** from **table_name** has unknown or missing type

### Actual behavior
column_name_1 is not visible for validation at all
